name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Commands
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver &
        sleep 10
        kill %1
    - name: autopep8
      id: autopep8
      uses: peter-evans/autopep8@v2
      with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
    - name: Fail if autopep8 made changes
      if: steps.autopep8.outputs.exit-code == 2
      run: exit 1
  
